baseURL = 'https://idgenero.github.io'
languageCode = 'pt-br'
title = 'IdGenero'

theme = "reveal-hugo"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
custom_theme = "reveal-hugo/themes/robot-lung.css"
